2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_setup.py:_flush():69] setting env: {}
2021-09-28 16:31:00,739 WARNING MainThread:3635 [wandb_setup.py:_flush():69] could not find program at scripts/train.py
2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_init.py:_log_setup():348] Logging user logs to /home/bhuwan/Desktop/cat-dog/outputs/2021-09-28/16-30-58/wandb/run-20210928_163100-1wqa5f2e/logs/debug.log
2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_init.py:_log_setup():349] Logging internal logs to /home/bhuwan/Desktop/cat-dog/outputs/2021-09-28/16-30-58/wandb/run-20210928_163100-1wqa5f2e/logs/debug-internal.log
2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_init.py:init():381] calling init triggers
2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {'lr': 0.0003, 'base_filters': 32, 'epochs': 2}
2021-09-28 16:31:00,739 INFO    MainThread:3635 [wandb_init.py:init():430] starting backend
2021-09-28 16:31:00,739 INFO    MainThread:3635 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-28 16:31:00,749 INFO    MainThread:3635 [backend.py:ensure_launched():135] starting backend process...
2021-09-28 16:31:00,753 INFO    MainThread:3635 [backend.py:ensure_launched():139] started backend process with pid: 3687
2021-09-28 16:31:00,754 INFO    MainThread:3635 [wandb_init.py:init():435] backend started and connected
2021-09-28 16:31:00,754 INFO    MainThread:3635 [wandb_init.py:init():494] updated telemetry
2021-09-28 16:31:00,755 INFO    MainThread:3635 [wandb_init.py:init():517] communicating current version
2021-09-28 16:31:01,289 INFO    MainThread:3635 [wandb_init.py:init():522] got version response 
2021-09-28 16:31:01,289 INFO    MainThread:3635 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-28 16:31:01,611 INFO    MainThread:3635 [wandb_init.py:init():557] starting run threads in backend
2021-09-28 16:31:06,614 INFO    MainThread:3635 [wandb_run.py:_console_start():1605] atexit reg
2021-09-28 16:31:06,614 INFO    MainThread:3635 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-28 16:31:06,614 INFO    MainThread:3635 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-28 16:31:06,615 INFO    MainThread:3635 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-28 16:31:06,615 INFO    MainThread:3635 [wandb_init.py:init():582] run started, returning control to user process
2021-09-28 16:31:06,780 INFO    MainThread:3635 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-09-28 16:31:06,780 INFO    MainThread:3635 [wandb_run.py:_restore():1547] restore
2021-09-28 16:31:09,128 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 654
}

2021-09-28 16:31:09,505 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 654
}

2021-09-28 16:31:09,659 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 16627
}

2021-09-28 16:31:09,763 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 23012
}

2021-09-28 16:31:09,866 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 654
  total_bytes: 23012
}

2021-09-28 16:31:09,969 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:10,072 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:10,174 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:10,276 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:10,379 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:10,483 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:11,031 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}

2021-09-28 16:31:11,749 INFO    MainThread:3635 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23012
  total_bytes: 23012
}
local_info {
}

2021-09-28 16:31:12,910 INFO    MainThread:3635 [wandb_run.py:_show_files():1947] logging synced files
